FROM tensorflow/tensorflow:latest-gpu
RUN apt-get -y install curl python-software-properties && \
  curl -sL https://deb.nodesource.com/setup_11.x | bash - &&\
  apt-get install -y nodejs
WORKDIR /app
ADD . .
RUN npm i